import logging
import subprocess
import pyautogui
from typing import Any, Tuple, Dict, List, Callable, Optional

# Although not explicitly listed for this file, the config module is a common
# dependency for components to access global settings.
# from . import config


class ActionExecutor:
    """
    Executes agent-generated Python code snippets in a controlled environment.

    This class serves as a secure bridge between the agent's reasoning module
    and the operating system. It exposes a limited set of safe functions
    (wrappers around `pyautogui` and `subprocess`) to the code being executed,
    preventing arbitrary code execution and providing a stable API for OS
    interaction.
    """

    def __init__(self, config: Optional[Any] = None) -> None:
        """
        Initializes the ActionExecutor.

        Args:
            config (Optional[Any]): A configuration object containing settings
                                    such as execution timeouts, logging levels,
                                    or safety constraints. Defaults to None.
        """
        self.logger = logging.getLogger(__name__)
        self.config = config
        self._action_space = self._build_action_space()
        self.logger.info("ActionExecutor initialized.")

    def _build_action_space(self) -> Dict[str, Callable]:
        """
        Constructs the dictionary of functions allowed in the exec scope.

        This method defines the "sandbox" for the agent's code. Only the
        functions defined here are callable by the generated code snippets.

        Returns:
            Dict[str, Callable]: A dictionary mapping function names (as strings)
                                 to their callable implementations.
        """
        return {
            "click": self._click,
            "typewrite": self._typewrite,
            "press_keys": self._press_keys,
            "scroll": self._scroll,
            "run_command": self._run_command,
        }

    def execute_action(self, code_string: str) -> Tuple[bool, str]:
        """
        Executes a string of Python code within the controlled environment.

        It uses Python's `exec()` function, but with a restricted `globals`
        dictionary defined by `_build_action_space()`. This ensures the agent
        can only call pre-approved, safe functions.

        Args:
            code_string (str): The Python code snippet generated by the agent to be executed.

        Returns:
            Tuple[bool, str]: A tuple containing:
                              - A boolean indicating if the execution was successful.
                              - A string containing the return value of the code,
                                its stdout, or an error message if it failed.
        """
        self.logger.info(f"Executing code: {code_string}")
        # Create a restricted environment for exec
        # Only functions from our action space are available
        restricted_globals = {
            "__builtins__": {},
            **self._action_space
        }

        try:
            # We can use a local dict to capture any return value from the code
            local_scope = {}
            exec(code_string, restricted_globals, local_scope)
            
            # Assuming the agent code might store its result in a 'result' variable
            result_val = local_scope.get('result', "No return value.")

            return (True, str(result_val))

        except Exception as e:
            self.logger.error(f"Error executing action code: {e}", exc_info=True)
            return (False, str(e))

    # --- Private Wrapper Methods for the Action Space ---

    def _click(self, x: int, y: int, button: str = 'left') -> str:
        """
        Secure wrapper for `pyautogui.click`.

        Args:
            x (int): The x-coordinate of the click location.
            y (int): The y-coordinate of the click location.
            button (str): The mouse button to use ('left', 'right', 'middle').

        Returns:
            str: A confirmation message of the action performed.
        """
        try:
            pyautogui.click(x=x, y=y, button=button)
            msg = f"Clicked {button} at ({x}, {y})"
            self.logger.info(msg)
            return msg
        except Exception as e:
            self.logger.error(f"Click action failed: {e}")
            raise

    def _typewrite(self, text: str, interval: float = 0.01) -> str:
        """
        Secure wrapper for `pyautogui.typewrite`.

        Args:
            text (str): The string of text to type.
            interval (float): The delay between each keystroke.

        Returns:
            str: A confirmation message of the action performed.
        """
        try:
            pyautogui.typewrite(text, interval=interval)
            msg = f"Typed text: '{text[:30]}...'"
            self.logger.info(msg)
            return msg
        except Exception as e:
            self.logger.error(f"Typewrite action failed: {e}")
            raise

    def _press_keys(self, keys: List[str]) -> str:
        """
        Secure wrapper for `pyautogui.hotkey` for pressing key combinations.

        Args:
            keys (List[str]): A list of key names to press simultaneously (e.g., ['ctrl', 'c']).

        Returns:
            str: A confirmation message of the action performed.
        """
        try:
            pyautogui.hotkey(*keys)
            msg = f"Pressed keys: {', '.join(keys)}"
            self.logger.info(msg)
            return msg
        except Exception as e:
            self.logger.error(f"Press keys action failed: {e}")
            raise

    def _scroll(self, amount: int, x: Optional[int] = None, y: Optional[int] = None) -> str:
        """
        Secure wrapper for `pyautogui.scroll`.

        Args:
            amount (int): The number of units to scroll. Positive for up, negative for down.
            x (Optional[int]): The x-coordinate of the mouse cursor for the scroll.
                               If None, uses the current mouse position.
            y (Optional[int]): The y-coordinate of the mouse cursor for the scroll.
                               If None, uses the current mouse position.

        Returns:
            str: A confirmation message of the action performed.
        """
        try:
            pyautogui.scroll(amount, x=x, y=y)
            direction = 'up' if amount > 0 else 'down'
            msg = f"Scrolled {direction} by {abs(amount)} units."
            self.logger.info(msg)
            return msg
        except Exception as e:
            self.logger.error(f"Scroll action failed: {e}")
            raise

    def _run_command(self, command: List[str]) -> str:
        """
        Secure wrapper for `subprocess.run` to execute shell commands.

        Executes a command and captures its output. Using a list of arguments
        is safer than a single string to prevent shell injection vulnerabilities.

        Args:
            command (List[str]): The command and its arguments as a list of strings.

        Returns:
            str: The combined stdout and stderr from the executed command.
        """
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=self.config.EXECUTION_TIMEOUT if self.config else 30,
                check=False,  # Don't raise exception for non-zero exit codes
                shell=False
            )
            output = f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
            self.logger.info(f"Ran command `{' '.join(command)}` with exit code {result.returncode}")
            return output
        except FileNotFoundError:
            err_msg = f"Command not found: {command[0]}"
            self.logger.error(err_msg)
            return f"STDERR: {err_msg}"
        except subprocess.TimeoutExpired:
            err_msg = "Command timed out."
            self.logger.error(err_msg)
            return f"STDERR: {err_msg}"
        except Exception as e:
            self.logger.error(f"Error running command: {e}")
            return f"STDERR: {e}"
